# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.10.3
branches:
  only:
    - master
notifications:
  email:
    recipients:
services:
  - mongodb
jdk:
  - oraclejdk8
